#%RAML 1.0 DataType
type: object
properties:
  Id:
    type: string
    description: Salesforce Account ID
  Name:
    type: string
  Phone?:
    type: string
  Website?:
    type: string
  Industry?:
    type: string
  Description?:
    type: string
  CreatedDate?:
    type: datetime
  LastModifiedDate?:
    type: datetime
